services:
  postgis:
    image: postgis/postgis:18-3.6
    container_name: postgis
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgis:/var/lib/postgresql
  pg_tileserv:
    image: pramsey/pg_tileserv:20250131
    container_name: pg_tileserv
    depends_on:
      - postgis
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PGPASSWORD}@postgis/${PG_DB}
    ports:
      - ${PG_TILESERV_PORT}:7800
    volumes:
      - pg_tileserv_config:/config
  pg_featureserv:
    image: pramsey/pg_featureserv:20250917
    container_name: pg_featureserv
    depends_on:
      - postgis
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PGPASSWORD}@postgis/${PG_DB}
    ports:
      - ${PG_FEATURESERV_PORT}:9000
    volumes:
      - pg_featureserv_config:/config
      - pg_featureserv_cache:/cache
      - pg_featureserv_assets:/assets
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin4
    depends_on:
      - postgis
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgis:
  pgadmin:
  pg_tileserv_config:
  pg_featureserv_config:
  pg_featureserv_cache:
  pg_featureserv_assets:
