local M = {
  { name = "1_l_s_with_bic_forbidden", area=false, node=false, displayName="1-lane street with bicycle forbidden" },
  { name = "2_l_s_with_bic_forbidden", area=false, node=false, displayName="2-lane street with bicycle forbidden" },
  { name = "3_l_s_with_bic_forbidden", area=false, node=false, displayName="3-lane street with bicycle forbidden" },
  { name = "4_l_s_with_bic_forbidden", area=false, node=false, displayName="4-lane street with bicycle forbidden" },
  { name = "5_l_s_with_bic_forbidden", area=false, node=false, displayName="5-lane street with bicycle forbidden" },
  { name = "6_l_s_with_bic_forbidden", area=false, node=false, displayName="6-lane street with bicycle forbidden" },
  { name = "7_l_s_with_bic_forbidden", area=false, node=false, displayName="7-lane street with bicycle forbidden" },
  { name = "1_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="1-lane street with bus/bicycle lane on one side" },
  { name = "2_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="2-lane street with bus/bicycle lane on one side" },
  { name = "3_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="3-lane street with bus/bicycle lane on one side" },
  { name = "4_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="4-lane street with bus/bicycle lane on one side" },
  { name = "5_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="5-lane street with bus/bicycle lane on one side" },
  { name = "6_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="6-lane street with bus/bicycle lane on one side" },
  { name = "7_l_s_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="7-lane street with bus/bicycle lane on one side" },
  { name = "1_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="1-lane street with bus/bicycle lane on both sides" },
  { name = "2_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="2-lane street with bus/bicycle lane on both sides" },
  { name = "3_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="3-lane street with bus/bicycle lane on both sides" },
  { name = "4_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="4-lane street with bus/bicycle lane on both sides" },
  { name = "5_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="5-lane street with bus/bicycle lane on both sides" },
  { name = "6_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="6-lane street with bus/bicycle lane on both sides" },
  { name = "7_l_s_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="7-lane street with bus/bicycle lane on both sides" },
  { name = "1_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="1-lane street with separate bicycle lane on sidewalk" },
  { name = "2_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="2-lane street with separate bicycle lane on sidewalk" },
  { name = "3_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="3-lane street with separate bicycle lane on sidewalk" },
  { name = "4_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="4-lane street with separate bicycle lane on sidewalk" },
  { name = "5_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="5-lane street with separate bicycle lane on sidewalk" },
  { name = "6_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="6-lane street with separate bicycle lane on sidewalk" },
  { name = "7_l_s_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="7-lane street with separate bicycle lane on sidewalk" },
  { name = "sep_bic_lane_on_sidewalk", area=false, node=false, displayName="Separate bicycle lane on sidewalk (marked as extra way)" },
  { name = "1_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="1-lane street with shared bicycle lane on carriageway" },
  { name = "2_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="2-lane street with shared bicycle lane on carriageway" },
  { name = "3_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="3-lane street with shared bicycle lane on carriageway" },
  { name = "4_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="4-lane street with shared bicycle lane on carriageway" },
  { name = "5_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="5-lane street with shared bicycle lane on carriageway" },
  { name = "6_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="6-lane street with shared bicycle lane on carriageway" },
  { name = "7_l_s_with_shared_bic_lane_on_carriageway", area=false, node=false, displayName="7-lane street with shared bicycle lane on carriageway" },
  { name = "1_l_s_with_no_bic_paths", area=true, node=false, displayName="1-lane street with no bicycle paths" },
  { name = "2_l_s_with_no_bic_paths", area=false, node=false, displayName="2-lane street with no bicycle paths" },
  { name = "3_l_s_with_no_bic_paths", area=false, node=false, displayName="3-lane street with no bicycle paths" },
  { name = "4_l_s_with_no_bic_paths", area=false, node=false, displayName="4-lane street with no bicycle paths" },
  { name = "5_l_s_with_no_bic_paths", area=false, node=false, displayName="5-lane street with no bicycle paths" },
  { name = "6_l_s_with_no_bic_paths", area=false, node=false, displayName="6-lane street with no bicycle paths" },
  { name = "7_l_s_with_no_bic_paths", area=false, node=false, displayName="7-lane street with no bicycle paths" },
  { name = "1_l_ows_with_bic_forbidden", area=false, node=false, displayName="1-lane one-way street with bicycle forbidden" },
  { name = "2_l_ows_with_bic_forbidden", area=false, node=false, displayName="2-lane one-way street with bicycle forbidden" },
  { name = "3_l_ows_with_bic_forbidden", area=false, node=false, displayName="3-lane one-way street with bicycle forbidden" },
  { name = "4_l_ows_with_bic_forbidden", area=false, node=false, displayName="4-lane one-way street with bicycle forbidden" },
  { name = "5_l_ows_with_bic_forbidden", area=false, node=false, displayName="5-lane one-way street with bicycle forbidden" },
  { name = "6_l_ows_with_bic_forbidden", area=false, node=false, displayName="6-lane one-way street with bicycle forbidden" },
  { name = "1_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="1-lane one-way street with bus/bicycle lane on one side" },
  { name = "2_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="2-lane one-way street with bus/bicycle lane on one side" },
  { name = "3_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="3-lane one-way street with bus/bicycle lane on one side" },
  { name = "4_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="4-lane one-way street with bus/bicycle lane on one side" },
  { name = "5_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="5-lane one-way street with bus/bicycle lane on one side" },
  { name = "6_l_ows_with_bus_bic_lane_on_one_side", area=false, node=false, displayName="6-lane one-way street with bus/bicycle lane on one side" },
  { name = "1_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="1-lane one-way street with bus/bicycle lane on both sides" },
  { name = "2_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="2-lane one-way street with bus/bicycle lane on both sides" },
  { name = "3_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="3-lane one-way street with bus/bicycle lane on both sides" },
  { name = "4_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="4-lane one-way street with bus/bicycle lane on both sides" },
  { name = "5_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="5-lane one-way street with bus/bicycle lane on both sides" },
  { name = "6_l_ows_with_bus_bic_lane_on_both_sides", area=false, node=false, displayName="6-lane one-way street with bus/bicycle lane on both sides" },
  { name = "1_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="1-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "2_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="2-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "3_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="3-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "4_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="4-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "5_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="5-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "6_l_ows_with_sep_bic_lane_on_sidewalk", area=false, node=false, displayName="6-lane one-way street with separate bicycle lane on sidewalk" },
  { name = "1_l_ows_with_no_bic_paths", area=false, node=false, displayName="1-lane one-way street with no bicycle paths" },
  { name = "2_l_ows_with_no_bic_paths", area=false, node=false, displayName="2-lane one-way street with no bicycle paths" },
  { name = "3_l_ows_with_no_bic_paths", area=false, node=false, displayName="3-lane one-way street with no bicycle paths" },
  { name = "4_l_ows_with_no_bic_paths", area=false, node=false, displayName="4-lane one-way street with no bicycle paths" },
  { name = "5_l_ows_with_no_bic_paths", area=false, node=false, displayName="5-lane one-way street with no bicycle paths" },
  { name = "6_l_ows_with_no_bic_paths", area=false, node=false, displayName="6-lane one-way street with no bicycle paths" },
  { name = "cycleroad", area=false, node=false, displayName="Cycleroad" },
  { name = "cycleway", area=false, node=false, displayName="Cycleway" },
  { name = "cycleway_multiuse", area=false, node=false, displayName="Cycleway multiuse (bicycle, pedestrian, mofa, moped)" },
  { name = "cyclist_waiting_aid", area=false, node=true, displayName="Cyclist waiting aid" },
  { name = "pedestrian", area=true, node=true, displayName="Mainly/exclusively for pedestrian" },
  { name = "pedestrian_with_bic_allowed", area=true, node=true, displayName="Mainly/exclusively for pedestrian with bicycle allowed" },
  { name = "path_with_bic_forbidden", area=false, node=false, displayName="Path with bicycle forbidden" },
  { name = "uncategorized", area=true, node=true, displayName="Uncategorized" },
}

return M